-- Seed existing portfolio companies from logos
INSERT INTO portfolios (name, status, logo_url) VALUES
  ('Amaze', 'active', '/assets/logos/logo-amaze.jpg'),
  ('Asblanc', 'active', '/assets/logos/logo-asblanc.png'),
  ('Bakkt', 'active', '/assets/logos/logo-bakkt.png'),
  ('Beam', 'active', '/assets/logos/logo-beam.png'),
  ('Blind', 'active', '/assets/logos/logo-blind.png'),
  ('Cellatoz', 'active', '/assets/logos/logo-cellatoz.jpg'),
  ('Foodinko', 'active', '/assets/logos/logo-foodinko.png'),
  ('GFFG', 'active', '/assets/logos/logo-gffg.png'),
  ('Helinox', 'active', '/assets/logos/logo-helinox.png'),
  ('K Bank', 'active', '/assets/logos/logo-kbank.png'),
  ('Klaytn', 'active', '/assets/logos/logo-klaytn.png'),
  ('Krafton', 'active', '/assets/logos/logo-krafton.png'),
  ('Lition', 'active', '/assets/logos/logo-lition.png'),
  ('LOT', 'active', '/assets/logos/logo-lot.png'),
  ('Metabora', 'active', '/assets/logos/logo-metabora.png'),
  ('Morenorisoft', 'active', '/assets/logos/logo-morenorisoft.png'),
  ('Musinsa', 'active', '/assets/logos/logo-musinsa.png'),
  ('Pemtobio', 'active', '/assets/logos/logo-pemtobio.jpg'),
  ('PLO', 'active', '/assets/logos/logo-plo.png'),
  ('PRGC', 'active', '/assets/logos/logo-prgc.png'),
  ('Rakumed', 'active', '/assets/logos/logo-rakumed.png'),
  ('Settle', 'active', '/assets/logos/logo-settle.png'),
  ('TCC', 'active', '/assets/logos/logo-tcc.png'),
  ('Techfloor', 'active', '/assets/logos/logo-techfloor.png'),
  ('TG', 'active', '/assets/logos/logo-tg.png'),
  ('TrustToken', 'active', '/assets/logos/logo-trusttoken.png');
