name = "abc-board"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

[site]
bucket = "./public"

[[routes]]
pattern = "app.abc-partners.com/*"
zone_name = "abc-partners.com"

[[d1_databases]]
binding = "DB"
database_name = "abc-board-db"
database_id = "9d48ddcd-4035-4e02-894f-9fbd0d998363"
